api_platform:
    title: Booking API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json:
            mime_types: ['application/json']
    error_formats:
        json:
            mime_types: ['application/json']
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    swagger:
        versions: [3]
        api_keys:
            Bearer:
                name: 'Authorization'
                type: header